
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:pass@db/main_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "679:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: